Linear Regression
OneStep-elecTRON/ContentSection pull request #17
Opened 2021-05-04 15:38 UTC by Anjali001

#10 
I've added the required changes. Let me know, if there's any issue.

2021-05-17 12:53 UTC, amansharma2910 requested changes
Great work on the content @Anjali001. Before I merge your PR, I need you to make a few changes, as listed below:
 - [x] Add breaks between paragraphs. Right now the content looks a bit congested.
 - [x] The image with the fomulae is not centered and has poor spacing. If possible, add some padding to the image.
 - [x] If possible, add some more content explanation about regression and supervised learning in general. Right now the explanation is concise and to the point, but we need to content for learners who are beginners.
 - [ ] Mention the resources that you referred to, if any.

2021-05-18 04:59 UTC, Anjali001 commented
@amansharma2910 Sure. I'll do the required changes asap.

2021-05-23 08:45 UTC, Anjali001 commented
@amansharma2910 I've done the changes you requested. Please check and let me know if there's an issue. Also, I've added some content from my own article on medium (I've added it as reference too), I hope that's not a problem.

2021-05-29 21:54 UTC, amansharma2910 approved these changes

2021-05-29 21:57 UTC, merged